[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = ['zsh', 'sh']

[[plugins]]
repo = 'Shougo/deoplete-clangx'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['context_filetype.vim']
on_event = 'InsertEnter'
hook_source = '''
    source ~/.vim/plugins/deoplete.vim
    call deoplete#enable()
'''
