[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    source ~/.vim/plugins/ale.vim
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = { 'colorscheme': 'tender' }
'''
