if !&compatible
    set nocompatible
endif

function! s:source_rc(path) abort
  let abspath = resolve(expand('~/.vim/rc/' . a:path))
  execute 'source' fnameescape(abspath)
endfunction

"reset augroup
augroup MyAutoCmd
    autocmd!
augroup END
augroup filetypedetect
augroup END

let g:python3_host_prog = $HOME.'/anaconda3/bin/python'

call s:source_rc('dein.vim')
call s:source_rc('map.vim')
call s:source_rc('command.vim')
call s:source_rc('option.vim')
